### ISSUE TITLE
Error in assignment1

### ISSUE THREAD

**Issue by Tetlanesh** [ZacBi/CS224n-2019#2]
Hey, I was googling github 224n to compare my solutions to others and stumbled on Your repo. While browsing I noticed that you have an error that is not catched by sanity code in assigment1  - Question 1.2: Implement compute_co_occurrence_matrix

`M = np.where(M > 0, 1, 0)`

This will turn all numbers greater than 1 into 1 while co-occurrence matrix as stated in the assignment itself (and in literature) is the COUNT of co-occurrence of words. Unfortunately the example provided in sanity check code by authors is badly designed as no co-occurrence is greater than 1 in those sentences therefore Your code passes. Here is the quote from assigment definition of co-occurence matrix:

> [...] We build a co-occurrence matrix $M$, which is a symmetric word-by-word matrix in which $M_{ij}$ is **the number of times** $w_j$ appears inside $w_i$'s window.

Removing this line solve half of the problem as now You are assigning co-ocurence twice:

`M[outside_idx, center_idx] += 1`
`M[center_idx, outside_idx] += 1`

Note that You are iterating over all words in a document so when assigning values for word2 to co-occur with word1 and word3 (and vice-versa) in next iteration you will assign values for word3 to co-occur with word2 and word4 (and vice-versa) therefore assigning word2<->word3 twice in both direction

All you need is one assignment and the symmetric nature of the problem will fill the symmetric co-occurrence in later iteration.

**Comment by ZacBi** [comment]
**Thank you!!!**
I have to admit this is a big mistake and I didn't check my answers after finishing a1. You've taught a good lesson for me. 
At that time I was a freshman to DL and coding. So what I think is why I can't pass the sanity check, so I left it by using `M = np.where(M > 0, 1, 0)`, and now I am ashamed about it. The code has been modified and thank your correction and explanation again!
